name: Run Docker Image from Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'trigger/**'
  workflow_dispatch:
    inputs:
      ID:
        description: 'ID'
        required: true
      InvokeName:
        description: 'FunctionInvoke'
        required: true

jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      INPUT_ID: ${{ github.event.inputs.ID }}
      INPUT_INVOKENAME: ${{ github.event.inputs.InvokeName }}
      USER_TOKEN: ${{ secrets.USER_TOKEN }}
      CURRENT_REPO: ${{ github.repository }}
      PAYLOAD_REPO: ${{ vars.PAYLOAD_REPO }}
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Pull and run Docker image pass env
      run: |
        docker pull nanmu08/ghaction:api2
        docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e USER_TOKEN -e INPUT_ID -e INPUT_INVOKENAME -e CURRENT_REPO -e PAYLOAD_REPO nanmu08/ghaction:api2
